import { IContact } from '@/types/Contact';
import { mockRoles } from './role';

const mockContacts: IContact[] = [
  {
    id: '1a2b3c4d5e6f',
    vendor: 'VendorA',
    whatsappId: 'whatsapp123',
    name: 'John Doe',
    firstname: 'John',
    lastname: 'Doe',
    email: 'john.doe@example.com',
    birthday: '1990-05-14',
    gender: 'Male',
    contact_lists: [
      {
        id: 'cl1',
        name: 'VIP Clients',
        contacts_count: 15,
        user: {
          id: 'u1',
          role: mockRoles[0],
          vendor: 'VendorA',
          email: 'admin.vendorA@example.com',
          firstName: 'Admin',
          lastName: 'User',
          phoneNumber: '+123456789',
          dateOfBirth: '1985-06-01',
          gender: 'Male',
          countryCode: '+1',
          avatar: 'avatar1.png',
          whatappId: 'whatsapp001',
          subjectId: 'subj001',
          username: 'adminUser',
          position: 'Administrator',
          teams: []
        },
        created_at: '2023-01-01T10:00:00Z'
      }
    ],
    country_code: '+1',
    phone: '1234567890',
    company: 'Tech Solutions',
    job_title: 'Software Engineer',
    user: {
      id: 'u1',
      role: mockRoles[0],
      vendor: 'VendorA',
      email: 'admin.vendorA@example.com',
      firstName: 'Admin',
      lastName: 'User',
      phoneNumber: '+123456789',
      dateOfBirth: '1985-06-01',
      gender: 'Male',
      countryCode: '+1',
      avatar: 'avatar1.png',
      whatappId: 'whatsapp001',
      subjectId: 'subj001',
      username: 'adminUser',
      position: 'Administrator',
      teams: []
    },
    created_at: '2023-01-01T10:00:00Z',
    updated_at: '2023-06-01T15:00:00Z',
    last_user_contacted_at: '2023-05-30T10:00:00Z',
    last_customer_contacted_at: '2023-05-29T14:00:00Z'
  },
  {
    id: '7g8h9i0j1k2l',
    vendor: 'VendorB',
    whatsappId: 'whatsapp456',
    name: 'Jane Smith',
    firstname: 'Jane',
    lastname: 'Smith',
    email: 'jane.smith@example.com',
    birthday: '1985-03-22',
    contact_lists: [
      {
        id: 'cl2',
        name: 'Marketing Team',
        contacts_count: 10,
        user: {
          id: 'u2',
          role: mockRoles[1],
          vendor: 'VendorB',
          email: 'manager.vendorB@example.com',
          firstName: 'Alex',
          lastName: 'Manager',
          phoneNumber: '+987654321',
          dateOfBirth: '1980-04-20',
          gender: 'Female',
          countryCode: '+44',
          avatar: 'avatar2.png',
          whatappId: 'whatsapp002',
          subjectId: 'subj002',
          username: 'managerAlex',
          position: 'Team Manager',
          teams: []
        },
        created_at: '2023-02-15T11:30:00Z'
      }
    ],
    country_code: '+44',
    phone: '987654321',
    company: 'Innovatech',
    job_title: 'Marketing Manager',
    user: {
      id: 'u2',
      role: mockRoles[1],
      vendor: 'VendorB',
      email: 'manager.vendorB@example.com',
      firstName: 'Alex',
      lastName: 'Manager',
      phoneNumber: '+987654321',
      dateOfBirth: '1980-04-20',
      gender: 'Female',
      countryCode: '+44',
      avatar: 'avatar2.png',
      whatappId: 'whatsapp002',
      subjectId: 'subj002',
      username: 'managerAlex',
      position: 'Team Manager',
      teams: []
    },
    created_at: '2023-02-15T11:30:00Z',
    updated_at: '2023-06-10T16:45:00Z',
    last_user_contacted_at: '2023-05-25T09:15:00Z',
    last_customer_contacted_at: '2023-05-24T13:20:00Z'
  },
  {
    id: '3m4n5o6p7q8rsdfgsdfg',
    vendor: 'VendorC',
    whatsappId: 'whatsapp789',
    name: 'Random User',
    firstname: 'Random',
    lastname: 'User',
    email: 'random.user@example.com',
    country_code: '+91',
    phone: '8001234567',
    created_at: '2023-03-10T14:20:00Z',
    updated_at: '2023-05-01T12:50:00Z',
    gender: 'Non-Binary',
    contact_lists: [],
    user: {
      id: 'u3',
      role: mockRoles[2],
      vendor: 'VendorC',
      email: 'support.vendorC@example.com',
      firstName: 'Support',
      lastName: 'Agent',
      phoneNumber: '+8001234567',
      dateOfBirth: '1995-08-15',
      gender: 'Non-Binary',
      countryCode: '+91',
      avatar: 'avatar3.png',
      whatappId: 'whatsapp003',
      subjectId: 'subj003',
      username: 'supportAgent',
      position: 'Customer Support',
      teams: []
    }
  },
  {
    id: '1a2b3c4d5e6khj',
    vendor: 'VendorA',
    whatsappId: 'whatsapp123',
    name: 'John Doe',
    firstname: 'John',
    lastname: 'Doe',
    email: 'john.doe@example.com',
    birthday: '1990-05-14',
    gender: 'Male',
    contact_lists: [
      {
        id: 'cl1',
        name: 'VIP Clients',
        contacts_count: 15,
        user: {
          id: 'u1',
          role: mockRoles[0],
          vendor: 'VendorA',
          email: 'admin.vendorA@example.com',
          firstName: 'Admin',
          lastName: 'User',
          phoneNumber: '+123456789',
          dateOfBirth: '1985-06-01',
          gender: 'Male',
          countryCode: '+1',
          avatar: 'avatar1.png',
          whatappId: 'whatsapp001',
          subjectId: 'subj001',
          username: 'adminUser',
          position: 'Administrator',
          teams: []
        },
        created_at: '2023-01-01T10:00:00Z'
      }
    ],
    country_code: '+1',
    phone: '1234567890',
    company: 'Tech Solutions',
    job_title: 'Software Engineer',
    user: {
      id: 'u1',
      role: mockRoles[0],
      vendor: 'VendorA',
      email: 'admin.vendorA@example.com',
      firstName: 'Admin',
      lastName: 'User',
      phoneNumber: '+123456789',
      dateOfBirth: '1985-06-01',
      gender: 'Male',
      countryCode: '+1',
      avatar: 'avatar1.png',
      whatappId: 'whatsapp001',
      subjectId: 'subj001',
      username: 'adminUser',
      position: 'Administrator',
      teams: []
    },
    created_at: '2023-01-01T10:00:00Z',
    updated_at: '2023-06-01T15:00:00Z',
    last_user_contacted_at: '2023-05-30T10:00:00Z',
    last_customer_contacted_at: '2023-05-29T14:00:00Z'
  },
  {
    id: '7g8h9i0j1k2asdasd',
    vendor: 'VendorB',
    whatsappId: 'whatsapp456',
    name: 'Jane Smith',
    firstname: 'Jane',
    lastname: 'Smith',
    email: 'jane.smith@example.com',
    birthday: '1985-03-22',
    contact_lists: [
      {
        id: 'cl2',
        name: 'Marketing Team',
        contacts_count: 10,
        user: {
          id: 'u2',
          role: mockRoles[1],
          vendor: 'VendorB',
          email: 'manager.vendorB@example.com',
          firstName: 'Alex',
          lastName: 'Manager',
          phoneNumber: '+987654321',
          dateOfBirth: '1980-04-20',
          gender: 'Female',
          countryCode: '+44',
          avatar: 'avatar2.png',
          whatappId: 'whatsapp002',
          subjectId: 'subj002',
          username: 'managerAlex',
          position: 'Team Manager',
          teams: []
        },
        created_at: '2023-02-15T11:30:00Z'
      }
    ],
    country_code: '+44',
    phone: '987654321',
    company: 'Innovatech',
    job_title: 'Marketing Manager',
    user: {
      id: 'u2',
      role: mockRoles[1],
      vendor: 'VendorB',
      email: 'manager.vendorB@example.com',
      firstName: 'Alex',
      lastName: 'Manager',
      phoneNumber: '+987654321',
      dateOfBirth: '1980-04-20',
      gender: 'Female',
      countryCode: '+44',
      avatar: 'avatar2.png',
      whatappId: 'whatsapp002',
      subjectId: 'subj002',
      username: 'managerAlex',
      position: 'Team Manager',
      teams: []
    },
    created_at: '2023-02-15T11:30:00Z',
    updated_at: '2023-06-10T16:45:00Z',
    last_user_contacted_at: '2023-05-25T09:15:00Z',
    last_customer_contacted_at: '2023-05-24T13:20:00Z'
  },
  {
    id: '3m4n5o6p7q8rewrqwer',
    vendor: 'VendorC',
    whatsappId: 'whatsapp789',
    name: 'Random User',
    firstname: 'Random',
    lastname: 'User',
    email: 'random.user@example.com',
    country_code: '+91',
    phone: '8001234567',
    created_at: '2023-03-10T14:20:00Z',
    updated_at: '2023-05-01T12:50:00Z',
    gender: 'Non-Binary',
    contact_lists: [],
    user: {
      id: 'u3',
      role: mockRoles[2],
      vendor: 'VendorC',
      email: 'support.vendorC@example.com',
      firstName: 'Support',
      lastName: 'Agent',
      phoneNumber: '+8001234567',
      dateOfBirth: '1995-08-15',
      gender: 'Non-Binary',
      countryCode: '+91',
      avatar: 'avatar3.png',
      whatappId: 'whatsapp003',
      subjectId: 'subj003',
      username: 'supportAgent',
      position: 'Customer Support',
      teams: []
    }
  },
  {
    id: '1a2b3c4d5e6lk',
    vendor: 'VendorA',
    whatsappId: 'whatsapp123',
    name: 'John Doe',
    firstname: 'John',
    lastname: 'Doe',
    email: 'john.doe@example.com',
    birthday: '1990-05-14',
    gender: 'Male',
    contact_lists: [
      {
        id: 'cl1',
        name: 'VIP Clients',
        contacts_count: 15,
        user: {
          id: 'u1',
          role: mockRoles[0],
          vendor: 'VendorA',
          email: 'admin.vendorA@example.com',
          firstName: 'Admin',
          lastName: 'User',
          phoneNumber: '+123456789',
          dateOfBirth: '1985-06-01',
          gender: 'Male',
          countryCode: '+1',
          avatar: 'avatar1.png',
          whatappId: 'whatsapp001',
          subjectId: 'subj001',
          username: 'adminUser',
          position: 'Administrator',
          teams: []
        },
        created_at: '2023-01-01T10:00:00Z'
      }
    ],
    country_code: '+1',
    phone: '1234567890',
    company: 'Tech Solutions',
    job_title: 'Software Engineer',
    user: {
      id: 'u1',
      role: mockRoles[0],
      vendor: 'VendorA',
      email: 'admin.vendorA@example.com',
      firstName: 'Admin',
      lastName: 'User',
      phoneNumber: '+123456789',
      dateOfBirth: '1985-06-01',
      gender: 'Male',
      countryCode: '+1',
      avatar: 'avatar1.png',
      whatappId: 'whatsapp001',
      subjectId: 'subj001',
      username: 'adminUser',
      position: 'Administrator',
      teams: []
    },
    created_at: '2023-01-01T10:00:00Z',
    updated_at: '2023-06-01T15:00:00Z',
    last_user_contacted_at: '2023-05-30T10:00:00Z',
    last_customer_contacted_at: '2023-05-29T14:00:00Z'
  },
  {
    id: '7g8h9i0j1k2lzxczxc',
    vendor: 'VendorB',
    whatsappId: 'whatsapp456',
    name: 'Jane Smith',
    firstname: 'Jane',
    lastname: 'Smith',
    email: 'jane.smith@example.com',
    birthday: '1985-03-22',
    contact_lists: [
      {
        id: 'cl2',
        name: 'Marketing Team',
        contacts_count: 10,
        user: {
          id: 'u2',
          role: mockRoles[1],
          vendor: 'VendorB',
          email: 'manager.vendorB@example.com',
          firstName: 'Alex',
          lastName: 'Manager',
          phoneNumber: '+987654321',
          dateOfBirth: '1980-04-20',
          gender: 'Female',
          countryCode: '+44',
          avatar: 'avatar2.png',
          whatappId: 'whatsapp002',
          subjectId: 'subj002',
          username: 'managerAlex',
          position: 'Team Manager',
          teams: []
        },
        created_at: '2023-02-15T11:30:00Z'
      }
    ],
    country_code: '+44',
    phone: '987654321',
    company: 'Innovatech',
    job_title: 'Marketing Manager',
    user: {
      id: 'u2',
      role: mockRoles[1],
      vendor: 'VendorB',
      email: 'manager.vendorB@example.com',
      firstName: 'Alex',
      lastName: 'Manager',
      phoneNumber: '+987654321',
      dateOfBirth: '1980-04-20',
      gender: 'Female',
      countryCode: '+44',
      avatar: 'avatar2.png',
      whatappId: 'whatsapp002',
      subjectId: 'subj002',
      username: 'managerAlex',
      position: 'Team Manager',
      teams: []
    },
    created_at: '2023-02-15T11:30:00Z',
    updated_at: '2023-06-10T16:45:00Z',
    last_user_contacted_at: '2023-05-25T09:15:00Z',
    last_customer_contacted_at: '2023-05-24T13:20:00Z'
  },
  {
    id: '3m4n5o6p7q8rzxcv',
    vendor: 'VendorC',
    whatsappId: 'whatsapp789',
    name: 'Random User',
    firstname: 'Random',
    lastname: 'User',
    email: 'random.user@example.com',
    country_code: '+91',
    phone: '8001234567',
    created_at: '2023-03-10T14:20:00Z',
    updated_at: '2023-05-01T12:50:00Z',
    gender: 'Non-Binary',
    contact_lists: [],
    user: {
      id: 'u3',
      role: mockRoles[2],
      vendor: 'VendorC',
      email: 'support.vendorC@example.com',
      firstName: 'Support',
      lastName: 'Agent',
      phoneNumber: '+8001234567',
      dateOfBirth: '1995-08-15',
      gender: 'Non-Binary',
      countryCode: '+91',
      avatar: 'avatar3.png',
      whatappId: 'whatsapp003',
      subjectId: 'subj003',
      username: 'supportAgent',
      position: 'Customer Support',
      teams: []
    }
  },
  {
    id: '1a2b3c4d5e6dfd',
    vendor: 'VendorA',
    whatsappId: 'whatsapp123',
    name: 'John Doe',
    firstname: 'John',
    lastname: 'Doe',
    email: 'john.doe@example.com',
    birthday: '1990-05-14',
    gender: 'Male',
    contact_lists: [
      {
        id: 'cl1',
        name: 'VIP Clients',
        contacts_count: 15,
        user: {
          id: 'u1',
          role: mockRoles[0],
          vendor: 'VendorA',
          email: 'admin.vendorA@example.com',
          firstName: 'Admin',
          lastName: 'User',
          phoneNumber: '+123456789',
          dateOfBirth: '1985-06-01',
          gender: 'Male',
          countryCode: '+1',
          avatar: 'avatar1.png',
          whatappId: 'whatsapp001',
          subjectId: 'subj001',
          username: 'adminUser',
          position: 'Administrator',
          teams: []
        },
        created_at: '2023-01-01T10:00:00Z'
      }
    ],
    country_code: '+1',
    phone: '1234567890',
    company: 'Tech Solutions',
    job_title: 'Software Engineer',
    user: {
      id: 'u1',
      role: mockRoles[0],
      vendor: 'VendorA',
      email: 'admin.vendorA@example.com',
      firstName: 'Admin',
      lastName: 'User',
      phoneNumber: '+123456789',
      dateOfBirth: '1985-06-01',
      gender: 'Male',
      countryCode: '+1',
      avatar: 'avatar1.png',
      whatappId: 'whatsapp001',
      subjectId: 'subj001',
      username: 'adminUser',
      position: 'Administrator',
      teams: []
    },
    created_at: '2023-01-01T10:00:00Z',
    updated_at: '2023-06-01T15:00:00Z',
    last_user_contacted_at: '2023-05-30T10:00:00Z',
    last_customer_contacted_at: '2023-05-29T14:00:00Z'
  },
  {
    id: '7g8h9i0j1k2lxcvxcv',
    vendor: 'VendorB',
    whatsappId: 'whatsapp456',
    name: 'Jane Smith',
    firstname: 'Jane',
    lastname: 'Smith',
    email: 'jane.smith@example.com',
    birthday: '1985-03-22',
    contact_lists: [
      {
        id: 'cl2',
        name: 'Marketing Team',
        contacts_count: 10,
        user: {
          id: 'u2',
          role: mockRoles[1],
          vendor: 'VendorB',
          email: 'manager.vendorB@example.com',
          firstName: 'Alex',
          lastName: 'Manager',
          phoneNumber: '+987654321',
          dateOfBirth: '1980-04-20',
          gender: 'Female',
          countryCode: '+44',
          avatar: 'avatar2.png',
          whatappId: 'whatsapp002',
          subjectId: 'subj002',
          username: 'managerAlex',
          position: 'Team Manager',
          teams: []
        },
        created_at: '2023-02-15T11:30:00Z'
      }
    ],
    country_code: '+44',
    phone: '987654321',
    company: 'Innovatech',
    job_title: 'Marketing Manager',
    user: {
      id: 'u2',
      role: mockRoles[1],
      vendor: 'VendorB',
      email: 'manager.vendorB@example.com',
      firstName: 'Alex',
      lastName: 'Manager',
      phoneNumber: '+987654321',
      dateOfBirth: '1980-04-20',
      gender: 'Female',
      countryCode: '+44',
      avatar: 'avatar2.png',
      whatappId: 'whatsapp002',
      subjectId: 'subj002',
      username: 'managerAlex',
      position: 'Team Manager',
      teams: []
    },
    created_at: '2023-02-15T11:30:00Z',
    updated_at: '2023-06-10T16:45:00Z',
    last_user_contacted_at: '2023-05-25T09:15:00Z',
    last_customer_contacted_at: '2023-05-24T13:20:00Z'
  },
  {
    id: '3m4n5o6p7q8r',
    vendor: 'VendorC',
    whatsappId: 'whatsapp789',
    name: 'Random User',
    firstname: 'Random',
    lastname: 'User',
    email: 'random.user@example.com',
    country_code: '+91',
    phone: '8001234567',
    created_at: '2023-03-10T14:20:00Z',
    updated_at: '2023-05-01T12:50:00Z',
    gender: 'Non-Binary',
    contact_lists: [],
    user: {
      id: 'u3',
      role: mockRoles[2],
      vendor: 'VendorC',
      email: 'support.vendorC@example.com',
      firstName: 'Support',
      lastName: 'Agent',
      phoneNumber: '+8001234567',
      dateOfBirth: '1995-08-15',
      gender: 'Non-Binary',
      countryCode: '+91',
      avatar: 'avatar3.png',
      whatappId: 'whatsapp003',
      subjectId: 'subj003',
      username: 'supportAgent',
      position: 'Customer Support',
      teams: []
    }
  }
];

export { mockContacts };
